### PR TITLE
draft `2024-11-20_escapecalc_update` blog post

### PR DESCRIPTION
**Pull request by jbloom**

### CODE REVIEW

**Comment by jbloom** [comment]
@Bernadetadad, I have pushed a draft post to our [lab blog](https://jbloomlab.org/posts/) about how mutations to the RBD affect neutralization, in the context of escape calculator update. I was planning on posting a similar Twitter thread too, but going forward I think I might also put substantive threads on the lab blog.

Can you review this post with your most critical eye, and let me know your thoughts?

To read the post, pull this branch `escape-calc-update-blog` of the lab webpage. Then just preview it. To do that, checkout the branch. Then build the `conda` environment in the repo, activate it with `conda activate jbloomlab.github.io`, run `npm install`, then run `npm run dev` and open the link that appears in the terminal to preview the website.

**Comment by WillHannon-MCB** [comment]
Actually, @Bernadetadad, all you need to do is follow [this preview link](https://deploy-preview-59--delicate-starship-6bdc01.netlify.app/). No need to pull in the changes locally and build it yourself.

**Comment by jbloom** [comment]
@WillHannon-MCB, that is cool! Did you do something special to generate that, or does GitHub Actions automatically generate the preview link?

**Comment by WillHannon-MCB** [comment]
@jbloom, it's a feature of Netlify! The final check 'Deploy Preview ready!' is where you find the link. It's on of the reasons I switched from hosting with GitHub pages to hosting with Netlify.

**Comment by Bernadetadad** [comment]
- typo at "(key sites of escape) in the RBD hvae"
- typo at "the escap calculator is not"
- I think 403/405/504 site escape is more nuanced than just up/down because while they do have negative correlation between binding and escape it's not as strong as many for other sites (-.62, -.59 and -.48, respectively) I think probably some antibodies do target these site but they are not major binding sites and perhaps their effect as RBD conformation changers is more important. I think your text is okay
- Rather than saying "we showed that sites that modulate RBD up-down positioning" I would change it to "our data indicates that sites that modulate RBD up-down positioning"
- That dms-viz coloring looks a little confusing because you highlight 4 sites but show heat map for only one of them and its's not clear if heatmap legend is for colour on the structure or for just site 405. I'm not sure you need that heatmap if you already have it in the post below (though using different colour scheme).

**Pull request merged**
